apiVersion: apps/v2beta1
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: giftrec
  replicas: 1
  template:
    metadata:
      labels:
        app: giftrec
    spec:
      containers:
      - name: flask
        image: yt338338/flask-template:v2
        env:
        - name: APP_SETTINGS
          value: config.DevelopmentConfig
        # - name: DATABASE_URL
        #    value: postgresql://localhost/my_app_db
        ports:
        - containerPort: 5000
